### ISSUE TITLE
Issue with negative decimal number without integer part

### ISSUE THREAD

**Issue by outaTiME** [NickKaramoff/pretty-money#11]
I am using the following code and it removes the integer part, the output should be `-0,5` but it is `-,5`, is this correct? or could it be solved?

```js
prettyMoney(
  {
    decimalDelimiter: ',',
    thousandsDelimiter: '.',
    minDecimal: 0,
    maxDecimal: 2,
  },
  -0.5
) // outputs: '-,50'
```

If you try it on your example page with the default configuration, the same thing happens 😢

**Comment by outaTiME** [comment]
BTW, as you see `minDecimal` setting is ignored too 😭

**Comment by kytta** [comment]
Yup, can see the issue. I'll try to look into it this week and fix it.

> BTW, as you see `minDecimal` setting is ignored too 😭

Hmm, this one I actually can't confirm on the website 🤔

![image](https://user-images.githubusercontent.com/6566248/115348733-4e4fc280-a1b3-11eb-854d-2610554d4327.png)

But since I'm changing the algorithm completely it should also be fixed

**Comment by outaTiME** [comment]
Hi @NickKaramoff, 
with respect to `minDecimal`, as can be seen in my example I use `minDecimal: 0` and `maxDecimal: 2`, therefore the number should be displayed formatted with the number of decimal places entered (because it is in range) if `min` and `max` were `2` (as seen in your picture) it's okay to show two decimal places.

Notice that it has the same formatting effect putting 0, 2 as 2, 2:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/140472/115405520-b064f380-a1c4-11eb-952f-d21d34444bd5.png">

**Comment by kytta** [comment]
Ah, I see. For this effect you need to use the `fluid` mode. 

In the `minmax` mode the amount of decimal places is `minDecimal`, if possible, and `maxDecimal` otherwise. In the `fluid` mode the amount of decimal places is the one closest to the input number and clamped between `minDecimal` and `maxDecimal`

**Comment by outaTiME** [comment]
Understood, thanks for the clarification 🙌 

The setting name `minmax` means that both values are used as if they were `Intl.NumberFormat`.

Wouldn't it be better for the default to be `fluid` to avoid misinterpretations?

In some cases using this new setting generates problems with number rounding, here is the capture:

<img width="535" alt="image" src="https://user-images.githubusercontent.com/140472/115448877-97723780-a1f0-11eb-9233-e4e311463416.png">

**Comment by kytta** [comment]
I'm sorry, Ariel, but this project is now archived; I will not maintain it any further. Use [`Number.prototype.toLocaleString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString); it works correctly starting with Node 14, is built-in, and has no bugs.
